parser: !!str '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
overrides:
  - files:
      - '*.ts'
    extends:
      - airbnb-base
      - airbnb-typescript/base
      - prettier
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
    parserOptions:
      parser: '@typescript-eslint/parser'
      project: tsconfig.eslint.json
      sourceType: module
